# Generated by Django 2.0.5 on 2018-05-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.CharField(max_length=15, verbose_name='行政编码')),
                ('name', models.CharField(max_length=50, verbose_name='行政名称')),
                ('pid', models.CharField(max_length=15, verbose_name='上级行政编码')),
                ('level', models.IntegerField(verbose_name='行政等级')),
                ('classification_code', models.CharField(default='', max_length=5, verbose_name='城乡分类代码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'administrative_coding',
                'ordering': ('coding',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='项目名称')),
                ('supervision_bank', models.CharField(blank=True, max_length=255, verbose_name='资金监管银行')),
                ('supervision_acount', models.CharField(blank=True, max_length=255, verbose_name='监管帐号')),
                ('project_state', models.CharField(blank=True, max_length=255, verbose_name='项目状态')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='项目地址')),
                ('dev_company', models.CharField(blank=True, max_length=255, verbose_name='开发公司')),
                ('license_authority', models.CharField(blank=True, max_length=255, verbose_name='发证机关')),
                ('sale_permit', models.CharField(blank=True, max_length=255, verbose_name='预(现)售证名称')),
                ('license_key', models.CharField(blank=True, max_length=255, verbose_name='预(现)售许可证号')),
                ('online_saleable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='纳入网上可售面积')),
                ('online_saleable_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='纳入网上可售套数')),
                ('saleable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='当前可售面积')),
                ('saleable_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='当前可售套数')),
                ('sold_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='已售面积')),
                ('sold_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='已售套数')),
                ('residential_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='当前(住宅)可售面积')),
                ('residential_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='当前(住宅)可售套数')),
                ('sold_residential_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='已售(住宅)面积')),
                ('sold_residential_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='已售(住宅)套数')),
                ('reserve_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='预定面积')),
                ('reserve_flats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='预定套数')),
                ('saleable_parking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='车位可售套数')),
                ('saleable_garage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='车库可售套数')),
                ('sold_avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='已售(住宅)平均价')),
                ('districts', models.CharField(blank=True, max_length=255, verbose_name='所在区县')),
                ('contact_phone', models.CharField(blank=True, max_length=255, verbose_name='售楼电话')),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='最高单价(住宅)')),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='最低单价(住宅)')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'new_house',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProxyIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip地址')),
                ('port', models.CharField(max_length=10, verbose_name='端口号')),
                ('speed', models.IntegerField(verbose_name='网速')),
                ('proxy_type', models.CharField(default='HTTP', max_length=10, verbose_name='代理类型')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proxy_ip',
                'ordering': ('created',),
                'managed': True,
            },
        ),
    ]
