# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_data',
            fields=[
                ('iAutoId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=256)),
            ],
        ),
    ]
