# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('supervision_bank', models.CharField(max_length=255, verbose_name='资金监管银行')),
                ('supervision_acount', models.CharField(max_length=255, verbose_name='监管帐号')),
                ('project_state', models.CharField(max_length=255, verbose_name='项目状态')),
                ('address', models.CharField(max_length=255, verbose_name='项目地址')),
                ('dev_company', models.CharField(max_length=255, verbose_name='开发公司')),
                ('license_authority', models.CharField(max_length=255, verbose_name='发证机关')),
                ('sale_permit', models.CharField(max_length=255, verbose_name='预(现)售证名称')),
                ('license_key', models.CharField(max_length=255, verbose_name='预(现)售许可证号')),
                ('online_saleable_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='纳入网上可售面积')),
                ('online_saleable_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='纳入网上可售套数')),
                ('saleable_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前可售面积')),
                ('saleable_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前可售套数')),
                ('sold_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已售面积')),
                ('sold_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已售套数')),
                ('residential_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前(住宅)可售面积')),
                ('residential_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前(住宅)可售套数')),
                ('sold_residential_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已售(住宅)面积')),
                ('sold_residential_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已售(住宅)套数')),
                ('reserve_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预定面积')),
                ('reserve_flats', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预定套数')),
                ('saleable_parking_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='车位可售套数')),
                ('saleable_garage_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='车库可售套数')),
                ('sold_avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已售(住宅)平均价')),
                ('districts', models.CharField(max_length=255, verbose_name='所在区县')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='售楼电话')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'managed': True,
                'db_table': 'new_house',
            },
        ),
    ]
