# Generated by Django 2.0.5 on 2018-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhouse',
            name='online_saleable_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='纳入网上可售面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='online_saleable_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='纳入网上可售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='remark',
            field=models.CharField(blank=True, default=0, max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='reserve_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='预定面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='reserve_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='预定套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='residential_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='当前(住宅)可售面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='residential_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='当前(住宅)可售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='saleable_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='当前可售面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='saleable_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='当前可售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='saleable_garage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='车库可售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='saleable_parking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='车位可售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='sold_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='已售面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='sold_avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='已售(住宅)平均价'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='sold_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='已售套数'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='sold_residential_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='已售(住宅)面积'),
        ),
        migrations.AlterField(
            model_name='newhouse',
            name='sold_residential_flats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='已售(住宅)套数'),
        ),
    ]
